name: Generate Jurisdiction Analytics Reports
on:
# push:   branches: [ main ]
 schedule:
 - cron: '40 11 * * *'  # everyday
 workflow_dispatch:
jobs:
 generate-reports:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout Repository
       uses: actions/checkout@v3
     - name: Set Up Python
       uses: actions/setup-python@v4
       with:
         python-version: '3.11'
     - name: Install Dependencies
       run: |
         pip install pandas ckanapi tabulate
     - name: Run Report Generation
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Pass GitHub's built-in token
       run: python JURISDICTION_ANALYTICS_REPORT/jurisdiction_analytics.py
     - name: commit files
       run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "updates" --allow-empty
          git push -f
