name: Update CKAN Datastore Stats
on:
  schedule:
    - cron: '10 10 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pandas ujson tqdm

      - name: Run script
        working-directory: datastore_tracker    
        run: |
          python ds_tracker.py

      - name: Commit CSV
        working-directory: datastore_tracker    
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add DS_num_tracker.csv ds-resources.csv org_stats.csv
          git commit -m "Auto-update DS_num_tracker.csv [skip ci]"
          git push
