name: run JSON LINES catalogue file download

on:
  schedule:
    - cron: '* 12 1,28-31 * *' # 1st and 28 to 31 of the month 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt
          
      - name: execute py script 
        run: python Catalogue_download/cat_down.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "add new cat file" --allow-empty)
          git push
      
          
     
